query GetAllPosts($limit: Int!, $cursor: PostCursor) {
  getAllPosts(limit: $limit, cursor: $cursor) {
    posts {
      id,
      title,
      createdAt,
      updatedAt,
      creator {
        id,
        username
      }
    },
    hasMore
  }
}